# Generated by Django 5.1.1 on 2024-09-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_user_id_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
