# Generated by Django 5.1.1 on 2024-10-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_feedback'),
        ('users', '0003_itella_user'),
    ]

    operations = [
    ]
