# Generated by Django 5.1.1 on 2024-10-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_apartment_number'),
        ('users', '0006_alter_address_phone_number'),
    ]

    operations = [
    ]
