# Generated by Django 5.1.1 on 2024-10-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20241001_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='apartment_number',
        ),
    ]
