# Generated by Django 5.1.1 on 2024-10-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_address_apartment_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
    ]
