# Generated by Django 5.1.1 on 2024-10-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_user_id_address_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
