# Generated by Django 5.1.1 on 2024-10-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderAddress',
        ),
    ]
