# Generated by Django 5.1.1 on 2024-09-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0007_order_address_order_city_order_country_order_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
