# Generated by Django 5.1.1 on 2024-10-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0010_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
