# Generated by Django 5.1.1 on 2024-10-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='products/img'),
        ),
    ]
