# Generated by Django 5.1.1 on 2024-12-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_title_en_product_title_es_product_title_et_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
